"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
[opener]
edit = [
	{ run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$1" & disown', desc = "Open", for = "linux" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
dragndrop = [
    { run = 'dragon-drop --on-top "$@"', desc = "Drag and drop" },
]

[open]
rules = [
	# Folder
	{ name = "*/", use = [ "edit", "open", "reveal", "dragndrop" ] },
	# Text
	{ mime = "text/*", use = [ "edit", "reveal", "dragndrop" ] },
	# Image
	{ mime = "image/*", use = [ "open", "reveal", "dragndrop" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal", "dragndrop" ] },
	# Archive
	{ mime = "application/{,g}zip", use = [ "extract", "reveal", "dragndrop" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal", "dragndrop" ] },
	# JSON
	{ mime = "application/{json,x-ndjson}", use = [ "edit", "reveal", "dragndrop" ] },
	{ mime = "*/javascript", use = [ "edit", "reveal", "dragndrop" ] },
	# Empty file
	{ mime = "inode/x-empty", use = [ "edit", "reveal", "dragndrop" ] },
	# Fallback
	{ name = "*", use = [ "open", "edit", "reveal", "dragndrop" ] },
]
