[general]
fullscreen = false
early-exit = true
# corners of rectangles round
corner-roundness = 0
# pointer, crop, line, arrow, rectangle, text, marker, blur, brush
initial-tool = "brush"
copy-command = "wl-copy"
annotation-size-factor = 0.5
# Might contain format specifiers: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
output-filename = "/home/dumbnerd/Pictures/Annotated/%B %d - %H:%M:%S.png"
save-after-copy = false
default-hide-toolbars = false
# block, freehand
primary-highlighter = "freehand"
disable-notifications = true
no-window-decoration = true
brush-smooth-history-size = 3
# Actions to trigger on right click (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-right-click = []
# Actions to trigger on Enter key (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-enter = ["save-to-clipboard"]
# Actions to trigger on Escape key (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-escape = ["exit"]

[font]
family = "Roboto"
style = "Bold"

[color-palette]
# These will be shown in the toolbar for quick selection
palette = ["#ffd700", "#00ffff", "#a52a2a", "#dc143c", "#ff1493", "#008000"]

# These will be available in the color picker as presets. Leave empty to use GTK's default
custom = []
