[general]
fullscreen = true
early-exit = true
# Select the tool on startup [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "brush"
copy-command = "wl-copy"
# Increase or decrease the size of the annotations
annotation-size-factor = 1
# Filename to use for saving action. Omit to disable saving to file. Might contain format specifiers: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
output-filename = "/home/dumbnerd/Pictures/Screenshots/%B %d | %H:%M:%S | output.png"
save-after-copy = true
default-hide-toolbars = false
primary-highlighter = "freehand"

[font]
family = "Roboto"
style = "Bold"

# custom colours for the colour palette
[color-palette]
first= "#00ffff"
second= "#a52a2a"
third= "#dc143c"
fourth= "#ff1493"
fifth= "#ffd700"
custom= "#008000"
