live_config_reload = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"   # #414868
blue = "0x7aa2f7"    # #7aa2f7
cyan = "0x7dcfff"    # #7dcfff
green = "0x9ece6a"   # #9ece6a
magenta = "0xbb9af7" # #bb9af7
red = "0xf7768e"     # #f7768e
white = "0xc0caf5"   # #c0caf5
yellow = "0xe0af68"  # #e0af68

[colors.normal]
black = "0x15161e"   # #15161e
blue = "0x7aa2f7"    # #7aa2f7
cyan = "0x7dcfff"    # #7dcfff
green = "0x9ece6a"   # #9ece6a
magenta = "0xbb9af7" # #bb9af7
red = "0xf7768e"     # #f7768e
# white = "0xa9b1d6"   # #a9b1d6
white = "0xffffff"
yellow = "0xe0af68"  # #e0af68

[colors.primary]
background = "0x000000" # default value : '#1a1b26' 
foreground = "0xc0caf5" # #c0caf5

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.45

padding = { x = 10, y = 10 }
